# Generated by Django 5.2.12 on 2026-08-10 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteVisitCounter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_visits', models.PositiveBigIntegerField(default=0)),
                ('first_visit_at', models.DateTimeField(blank=True, null=True)),
                ('last_visit_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'site visit counter',
                'verbose_name_plural': 'site visit counter',
            },
        ),
    ]
