# Generated by Django 5.2.12 on 2026-08-11 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailySiteVisit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('visits', models.PositiveBigIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'daily site visits',
                'verbose_name_plural': 'daily site visits',
                'ordering': ['-date'],
            },
        ),
    ]
