# Generated by Django 4.2.25 on 2025-10-21 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Project title', max_length=200, verbose_name='Title')),
                ('description', models.TextField(help_text='Detailed project description', verbose_name='Description')),
                ('short_description', models.CharField(blank=True, help_text='Brief project summary', max_length=300, verbose_name='Short Description')),
                ('image', models.ImageField(blank=True, help_text='Project image or screenshot', null=True, upload_to='projects/', verbose_name='Image')),
                ('url', models.URLField(blank=True, help_text='Live project URL', verbose_name='Project URL')),
                ('github_url', models.URLField(blank=True, help_text='GitHub repository URL', verbose_name='GitHub URL')),
                ('technologies', models.CharField(blank=True, help_text='Technologies used (comma-separated)', max_length=500, verbose_name='Technologies')),
                ('is_featured', models.BooleanField(default=False, help_text='Display in featured section', verbose_name='Featured')),
                ('order', models.IntegerField(default=0, help_text='Display order (lower numbers first)', verbose_name='Order')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
            ],
            options={
                'verbose_name': 'Project',
                'verbose_name_plural': 'Projects',
                'ordering': ['order', '-created_at'],
            },
        ),
    ]
