# Generated by Django 4.2.27 on 2026-08-10 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_projectcontent_projectcontenttranslation'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='visible',
            field=models.BooleanField(default=True),
        ),
    ]
