services:
  db:
    image: postgres:17
    container_name: portfolio_db
    restart: unless-stopped
    environment:
      POSTGRES_DB: postgres_db
      POSTGRES_USER: jalbert
      POSTGRES_PASSWORD: 23051988joswel
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  web:
    build: .
    container_name: portfolio_backend
    restart: unless-stopped
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/apps
    ports:
      - "8000:8000"
    environment:
      DB_NAME: postgres_db
      DB_USER: jalbert
      DB_PASSWORD: 23051988joswel
      DB_HOST: db
      DB_PORT: 5432
    depends_on:
      - db

volumes:
  postgres_data: postgres_data:
