services:
  db:
    image: postgres:17
    container_name: portfolio_db
    restart: unless-stopped
    environment:
      POSTGRES_DB: postgres_db
      POSTGRES_USER: jalbert
      POSTGRES_PASSWORD: 23051988joswel
    volumes:
      - postgres_data:/var/lib/postgresql/data

  web:
    build: .
    container_name: portfolio_backend
    restart: unless-stopped
    command: sh -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    working_dir: /apps
    volumes:
      - .:/apps
    ports:
      - "8000:8000"
    environment:
      DB_NAME: postgres_db
      DB_USER: jalbert
      DB_PASSWORD: 23051988joswel
      DB_HOST: db
      DB_PORT: 5432
      PYTHONUNBUFFERED: 1
      PYTHONDONTWRITEBYTECODE: 1
    depends_on:
      - db

volumes:
  postgres_data:
