# Generated by Django 5.2.12 on 2026-08-10 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactinquiry',
            name='confirmation_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contactinquiry',
            name='email_error',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='contactinquiry',
            name='notification_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
