# Generated by Django 4.2.25 on 2025-10-21 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutMe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Full name', max_length=200, verbose_name='Name')),
                ('title', models.CharField(help_text='Professional title or role', max_length=200, verbose_name='Professional Title')),
                ('bio', models.TextField(help_text='Short biography', verbose_name='Biography')),
                ('email', models.EmailField(help_text='Contact email', max_length=254, verbose_name='Email')),
                ('phone', models.CharField(blank=True, help_text='Contact phone number', max_length=20, verbose_name='Phone')),
                ('location', models.CharField(blank=True, help_text='City, Country', max_length=200, verbose_name='Location')),
                ('profile_image', models.ImageField(blank=True, help_text='Profile photo', null=True, upload_to='about/', verbose_name='Profile Image')),
                ('resume_file', models.FileField(blank=True, help_text='Resume or CV file', null=True, upload_to='about/resumes/', verbose_name='Resume/CV')),
                ('linkedin_url', models.URLField(blank=True, verbose_name='LinkedIn URL')),
                ('github_url', models.URLField(blank=True, verbose_name='GitHub URL')),
                ('twitter_url', models.URLField(blank=True, verbose_name='Twitter URL')),
                ('website_url', models.URLField(blank=True, verbose_name='Website URL')),
                ('is_active', models.BooleanField(default=True, help_text='Only one profile should be active at a time', verbose_name='Active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
            ],
            options={
                'verbose_name': 'About Me',
                'verbose_name_plural': 'About Me',
                'ordering': ['-created_at'],
            },
        ),
    ]
