# Generated by Django 4.2.27 on 2026-08-10 09:00

from django.db import migrations, models
import django.db.models.deletion
import parler.fields
import parler.models


class Migration(migrations.Migration):

    dependencies = [
        ('tech_details', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TechDetailContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tech_detail', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='localized_content', to='tech_details.techdetail')),
            ],
            options={
                'abstract': False,
            },
            bases=(parler.models.TranslatableModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='TechDetailContentTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('category', models.CharField(max_length=100)),
                ('text', models.CharField(max_length=255)),
                ('master', parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='tech_details.techdetailcontent')),
            ],
            options={
                'verbose_name': 'tech detail content Translation',
                'db_table': 'tech_details_techdetailcontent_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
                'unique_together': {('language_code', 'master')},
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
    ]
