# Generated by Django 4.2.25 on 2025-10-21 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Sender's name", max_length=200, verbose_name='Name')),
                ('email', models.EmailField(help_text="Sender's email", max_length=254, verbose_name='Email')),
                ('subject', models.CharField(help_text='Message subject', max_length=300, verbose_name='Subject')),
                ('message', models.TextField(help_text='Message content', verbose_name='Message')),
                ('phone', models.CharField(blank=True, help_text='Contact phone number', max_length=20, verbose_name='Phone')),
                ('is_read', models.BooleanField(default=False, help_text='Mark as read', verbose_name='Read')),
                ('is_replied', models.BooleanField(default=False, help_text='Mark as replied', verbose_name='Replied')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
            ],
            options={
                'verbose_name': 'Contact Message',
                'verbose_name_plural': 'Contact Messages',
                'ordering': ['-created_at'],
            },
        ),
    ]
