# Generated by Django 4.2.27 on 2026-08-10 12:49

import apps.resume.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('singleton', models.BooleanField(default=True, editable=False, unique=True)),
                ('file', models.FileField(upload_to='resumes/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf']), apps.resume.models.validate_resume_size, apps.resume.models.validate_pdf_signature])),
                ('public_filename', models.CharField(default='Jalberth_Mosquera_CV.pdf', max_length=160)),
                ('download_count', models.PositiveIntegerField(default=0, editable=False)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'CV',
                'verbose_name_plural': 'CV',
            },
        ),
    ]
