# Generated by Django 5.2.12 on 2026-04-01 10:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProblemSolution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('problem', models.TextField(blank=True)),
                ('solution', models.TextField(blank=True)),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='problem_solution', to='projects.project')),
            ],
            options={
                'verbose_name': 'Problem Solution',
                'verbose_name_plural': 'Problem Solutions',
            },
        ),
    ]
