# Generated by Django 4.2.25 on 2025-10-21 19:42

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SkillCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the skill category', max_length=100, verbose_name='Category Name')),
                ('description', models.TextField(blank=True, help_text='Category description', verbose_name='Description')),
                ('order', models.IntegerField(default=0, help_text='Display order (lower numbers first)', verbose_name='Order')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
            ],
            options={
                'verbose_name': 'Skill Category',
                'verbose_name_plural': 'Skill Categories',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the skill or technology', max_length=100, verbose_name='Skill Name')),
                ('proficiency', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced'), ('expert', 'Expert')], default='intermediate', help_text='Level of proficiency', max_length=20, verbose_name='Proficiency Level')),
                ('percentage', models.IntegerField(default=50, help_text='Proficiency percentage (0-100)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Percentage')),
                ('icon', models.CharField(blank=True, help_text='Icon class or URL', max_length=100, verbose_name='Icon')),
                ('description', models.TextField(blank=True, help_text='Skill description', verbose_name='Description')),
                ('years_experience', models.IntegerField(default=0, help_text='Years of experience with this skill', validators=[django.core.validators.MinValueValidator(0)], verbose_name='Years of Experience')),
                ('is_featured', models.BooleanField(default=False, help_text='Display in featured skills', verbose_name='Featured')),
                ('order', models.IntegerField(default=0, help_text='Display order within category', verbose_name='Order')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('category', models.ForeignKey(help_text='Skill category', on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='skills.skillcategory', verbose_name='Category')),
            ],
            options={
                'verbose_name': 'Skill',
                'verbose_name_plural': 'Skills',
                'ordering': ['category__order', 'order', 'name'],
            },
        ),
    ]
