name: Deploy to Railway

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  deploy:
    name: Deploy to Production
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy to Railway
        uses: bervProject/railway-deploy@main
        with:
          railway_token: ${{ secrets.RAILWAY_TOKEN }}
          service: ${{ secrets.RAILWAY_SERVICE }}

      - name: Wait for deployment
        run: sleep 30

      - name: Health check
        run: |
          # Add your production URL here
          if [ -n "${{ secrets.PRODUCTION_URL }}" ]; then
            echo "Checking production health..."
            response=$(curl -s -o /dev/null -w "%{http_code}" "${{ secrets.PRODUCTION_URL }}/api/health/" || echo "000")

            if [ "$response" = "200" ]; then
              echo "✓ Production is healthy!"
            else
              echo "⚠️ Health check returned status: $response"
            fi
          else
            echo "⚠️ PRODUCTION_URL not set, skipping health check"
          fi

  notify:
    name: Notify Deployment
    runs-on: ubuntu-latest
    needs: deploy
    if: always()

    steps:
      - name: Deployment notification
        run: |
          if [ "${{ needs.deploy.result }}" = "success" ]; then
            echo "✓ Deployment successful!"
          else
            echo "❌ Deployment failed!"
            exit 1
          fi
