export const translations = {
  en: {
    navHome: 'Home', navProjects: 'Projects', navAbout: 'About', navContact: 'Contact',
    heroGreeting: "Hi, I'm", heroRole: "I'm a Backend Developer.", heroDescription: "Deploying self-hosted solutions that drive a business' growth.", viewProjects: 'View Projects', downloadCv: 'Download CV', cvDownloading: 'Preparing your CV…', cvDownloaded: 'CV downloaded successfully', cvDownloadError: 'The CV could not be downloaded', cvEyebrow: 'Download CV', cvFormatTitle: 'Choose the right CV format', cvFormatDescription: 'Both versions are generated live using the latest information in the portfolio database.', cvConciseTitle: 'Concise CV', cvConciseDescription: 'Clean, white and ATS-friendly. Recommended for applications and recruitment platforms.', cvVisualTitle: 'Visual CV', cvVisualDescription: 'Complete dark presentation with portrait, color and a richer portfolio layout.', cvChoose: 'Download format', close: 'Close',
    featuredTitle: 'Featured Projects', featuredSubtitle: "Some of the real-world applications I've built and deployed.", viewAll: 'View All', viewAllProjects: 'View All Projects', featuredEmpty: 'Featured projects will appear here once they are published.',
    profile: 'Profile', techTitle: 'My Tech Stack', techSubtitle: 'Technologies I use to build and deploy applications, at scale.', techAlt: 'Self-hosted infrastructure stack',
    contactEyebrow: 'Contact', contactTitle: "Let's build something reliable.", contactIntro: 'Tell me about the company, role or backend problem you need to solve. Every inquiry is stored securely for follow-up.', company: 'Company or recruiter', companyPlaceholder: 'Company or recruiter name', phone: 'Phone', description: 'Description', descriptionPlaceholder: 'Describe the role, project or problem you would like to discuss.', send: 'Send message', sending: 'Sending…', sent: "Message received. I'll get back to you soon.", sendError: 'Your message could not be sent. Please try again.', formError: 'Please review the form and try again.',
    allProjects: 'All Projects', allProjectsSubtitle: "All the projects I've built and deployed.", projectsError: 'Projects could not be loaded. Please try again later.', projectsEmpty: 'New case studies are being prepared.', dataError: 'Live portfolio data is temporarily unavailable.',
    caseStudy: 'Case Study', projectNotFound: 'Project not found', projectLoadError: 'Failed to load project', back: 'Back', backProjects: 'Back to Projects', liveDemo: 'Live Demo', githubRepo: 'GitHub Repo', problem: 'The Problem', solution: 'The Solution', gallery: 'Gallery', techDetails: 'Tech Details', lessons: 'Lessons Learned', loading: 'Loading content', languageSelector: 'Language selector',
    notFoundEyebrow: 'Page not found', notFoundTitle: 'This route leads nowhere.', notFoundDescription: 'The address may be incorrect or the page may have moved. You can return home or continue exploring my projects.', notFoundHome: 'Back to home', notFoundProjects: 'View projects',
  },
  es: {
    navHome: 'Inicio', navProjects: 'Proyectos', navAbout: 'Sobre mí', navContact: 'Contacto',
    heroGreeting: 'Hola, soy', heroRole: 'Soy desarrollador backend.', heroDescription: 'Despliego soluciones autohospedadas que impulsan el crecimiento de negocios.', viewProjects: 'Ver proyectos', downloadCv: 'Descargar CV', cvDownloading: 'Preparando tu CV…', cvDownloaded: 'CV descargado correctamente', cvDownloadError: 'No se pudo descargar el CV', cvEyebrow: 'Descargar CV', cvFormatTitle: 'Elegí el formato que necesitás', cvFormatDescription: 'Ambas versiones se generan al instante con la información más reciente de la base de datos del portfolio.', cvConciseTitle: 'CV profesional', cvConciseDescription: 'Diseño blanco, limpio y compatible con sistemas ATS. Recomendado para candidaturas y portales de empleo.', cvVisualTitle: 'CV visual', cvVisualDescription: 'Presentación completa con fondo oscuro, fotografía, color y mayor riqueza visual.', cvChoose: 'Descargar formato', close: 'Cerrar',
    featuredTitle: 'Proyectos destacados', featuredSubtitle: 'Algunas aplicaciones reales que desarrollé y puse en producción.', viewAll: 'Ver todos', viewAllProjects: 'Ver todos los proyectos', featuredEmpty: 'Los proyectos destacados aparecerán aquí cuando se publiquen.',
    profile: 'Perfil', techTitle: 'Mi stack tecnológico', techSubtitle: 'Tecnologías que utilizo para construir y desplegar aplicaciones a escala.', techAlt: 'Infraestructura autohospedada',
    contactEyebrow: 'Contacto', contactTitle: 'Construyamos algo confiable.', contactIntro: 'Contame sobre la empresa, el puesto o el problema backend que necesitás resolver. Cada consulta se almacena de forma segura para su seguimiento.', company: 'Empresa o reclutador', companyPlaceholder: 'Nombre de la empresa o reclutador', phone: 'Teléfono', description: 'Descripción', descriptionPlaceholder: 'Describí el puesto, proyecto o problema que te gustaría conversar.', send: 'Enviar mensaje', sending: 'Enviando…', sent: 'Mensaje recibido. Me pondré en contacto pronto.', sendError: 'No se pudo enviar tu mensaje. Intentá nuevamente.', formError: 'Revisá el formulario e intentá nuevamente.',
    allProjects: 'Todos los proyectos', allProjectsSubtitle: 'Todos los proyectos que desarrollé y desplegué.', projectsError: 'No se pudieron cargar los proyectos. Intentá nuevamente más tarde.', projectsEmpty: 'Se están preparando nuevos casos de estudio.', dataError: 'Los datos del portfolio no están disponibles temporalmente.',
    caseStudy: 'Caso de estudio', projectNotFound: 'Proyecto no encontrado', projectLoadError: 'No se pudo cargar el proyecto', back: 'Volver', backProjects: 'Volver a proyectos', liveDemo: 'Ver proyecto', githubRepo: 'Repositorio GitHub', problem: 'El problema', solution: 'La solución', gallery: 'Galería', techDetails: 'Detalles técnicos', lessons: 'Aprendizajes', loading: 'Cargando contenido', languageSelector: 'Selector de idioma',
    notFoundEyebrow: 'Página no encontrada', notFoundTitle: 'Esta ruta no lleva a ningún sitio.', notFoundDescription: 'Puede que la dirección sea incorrecta o que la página se haya movido. Podés volver al inicio o seguir explorando mis proyectos.', notFoundHome: 'Volver al inicio', notFoundProjects: 'Ver proyectos',
  },
}
